# Generated by Django 3.2.3 on 2021-06-10 18:49

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('resume_id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('civil_state', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], default='Solteiro(a)', max_length=13)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=9)),
                ('postal_code', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=14)),
                ('linkedin', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('other_social_media', models.URLField()),
                ('description', models.TextField(max_length=500)),
                ('deficient_person', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('if_deficient', models.CharField(max_length=100)),
                ('scholarship_level', models.CharField(choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Completo'), ('Ensino Fundamental Completo', 'Ensino Fundamental Incompleto'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo')], max_length=50)),
                ('formation_kind', models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo'), ('Especialização', 'Especialização'), ('MBA', 'MBA'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=50)),
                ('education_institution', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('professional_objectives', models.TextField(max_length=500)),
                ('skills', models.TextField(max_length=500)),
                ('company', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('professional_area', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=99999999)),
                ('start_company_date', models.DateField()),
                ('finish_company_date', models.DateField()),
                ('function', models.TextField(verbose_name=500)),
                ('certifications', models.TextField(max_length=500)),
                ('languages', models.TextField(max_length=500)),
            ],
        ),
    ]
