# Generated by Django 3.2.3 on 2021-06-10 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='function',
        ),
        migrations.AddField(
            model_name='resume',
            name='function_role',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='published_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='finish_company_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='finish_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='formation_kind',
            field=models.CharField(blank=True, choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo'), ('Especialização', 'Especialização'), ('MBA', 'MBA'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='if_deficient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='other_social_media',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_area',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank='true', upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999),
        ),
        migrations.AlterField(
            model_name='resume',
            name='scholarship_level',
            field=models.CharField(blank=True, choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Completo'), ('Ensino Fundamental Completo', 'Ensino Fundamental Incompleto'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_company_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
