# Generated by Django 3.2.3 on 2021-06-10 20:12

import datetime
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210610_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birthday',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, max_length=500, verbose_name='Certificações'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='civil_state',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], default='Solteiro(a)', max_length=13, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.CharField(blank=True, max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='deficient_person',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Pessoa com deficiência?'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='district',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instituição de Ensino'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='finish_company_date',
            field=models.DateField(blank=True, verbose_name='Data do Fim (se houver)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='finish_date',
            field=models.DateField(blank=True, verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='formation_kind',
            field=models.CharField(blank=True, choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo'), ('Especialização', 'Especialização'), ('MBA', 'MBA'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pós-Doutorado', 'Pós-Doutorado')], max_length=50, verbose_name='Tipo de formação'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='function_role',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descreva as funções'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=9, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='if_deficient',
            field=models.CharField(blank=True, max_length=100, verbose_name='Se sim, descreva a deficiência'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, max_length=500, verbose_name='Linguagens'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='other_social_media',
            field=models.URLField(blank=True, verbose_name='Outra mídia social'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='postal_code',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_area',
            field=models.CharField(blank=True, max_length=30, verbose_name='Área profissional'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='professional_objectives',
            field=models.TextField(max_length=500, verbose_name='Objetivos profissionais'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank='true', upload_to='', verbose_name='Imagem de Perfil'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='published_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Publicado em: '),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Currículo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='role',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='scholarship_level',
            field=models.CharField(blank=True, choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Completo'), ('Ensino Fundamental Completo', 'Ensino Fundamental Incompleto'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo')], max_length=50, verbose_name='Nível de escolaridade'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(max_length=500, verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_company_date',
            field=models.DateField(blank=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='telephone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
