# Generated by Django 3.2.3 on 2021-06-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210610_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank='true', upload_to='pictures/%d/%m/%Y/', verbose_name='Imagem de Perfil'),
        ),
    ]
